

#1 What is the total revenue generated by male vs. female?
select gender, sum(purchase_amount)
from customer
group by gender;


#2 Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied= 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);


#3 Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "average_product_rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


#4 Compare the average purchase amount between standard and express shipping.
select avg(purchase_amount), shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


#5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc; 


#6 Which 5 products have the highest percentage of purchase with discount applied out of total purchase?
select item_purchased,
100 * count(case when discount_applied = "Yes" then item_purchased end)/count(*) as discount_purchase_percentage
from customer
group by item_purchased
order by discount_purchase_percentage desc
limit 5;


#7 Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
case
	when previous_purchases=1 then "New"
    when previous_purchases>=2 and previous_purchases<=10 then "Returning"
    else "Loyal" 
    end as customer_segment
from customer   
)

select customer_segment, count(*) as "Number of Customers"
from customer_type 
group by customer_segment;
    
    
    
#8 What are the 3 most purchased items within each category?
with ranked_items as (
select
      category,
      item_purchased,
      count(*) as total_purchases,
      row_number() over(partition by category order by count(*) desc) as rank_num
from customer
group by category, item_purchased
)

select 
      category,
      item_purchased,
      total_purchases
from 
     ranked_items
where
     rank_num <=3;     



#9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
subscription_status, 
count(customer_id) as repeated_buyers
from customer
where 
     previous_purchases > 5
group by
        subscription_status;


#10 What is the revenue contrubution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

 

